version: '3.8'

services:

  app:
    container_name: playground_streamlit
    build:
      context: .
      dockerfile: Dockerfile
      
    volumes:
      - .\workspace:/workspace

    ports:
      - 8001:8000

    command: /bin/sh -c "while sleep 1000; do :; done"